//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""gameplay"",
            ""id"": ""30a53fd5-aa6e-474a-bd92-5ff32652ab9e"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""dfc54b0b-f6ef-4f89-b387-19ed96323769"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""3f907e86-2154-4fb0-a99a-0662e2a65552"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""sprint"",
                    ""type"": ""Button"",
                    ""id"": ""1e262a19-83fd-4b61-89e4-655bac9807ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""basicatk"",
                    ""type"": ""Button"",
                    ""id"": ""23a6abfc-c569-4b4f-a8a7-f2d80e584bc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""skill1"",
                    ""type"": ""Button"",
                    ""id"": ""01d866fb-67cb-4e92-bbc2-22910384de29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""skill2"",
                    ""type"": ""Button"",
                    ""id"": ""b107dc0c-4982-4e6f-99cf-362f0cc66032"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""skill3"",
                    ""type"": ""Button"",
                    ""id"": ""2a289d41-0dd8-4abb-86bb-2d9b5af03fce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""skill4"",
                    ""type"": ""Button"",
                    ""id"": ""e6f48ef6-133e-439b-a99b-5105d270c1bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Dpad"",
                    ""id"": ""548dba84-e51e-4b4d-8720-5c83b7f96025"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2c3b7a1d-b84e-487d-8f9c-7531d2f787d5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b7738889-bbbd-4140-9687-1b0295be740c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a8c37ba0-6104-4076-8656-666c62f38712"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c3065c1b-c792-4079-8a29-b5927e40481a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e36be98e-481f-4adf-93dc-181e2ac8b240"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9935ca6f-4964-4bd4-bea3-6cfadd023750"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2041441-bffe-433f-834e-976c9dc5d3d7"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95bb9430-a511-43b9-9923-ffe45af992ba"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7d8434a-092f-40eb-98d4-82b1bfdb8323"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38a6de8d-40db-4aea-823a-4935fb7914d5"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""basicatk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bff906f-9c38-456d-a198-9d1a3e6752dd"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""basicatk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e31bba1-67a4-4bfc-8115-bbfab6d000a5"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e00a63ab-ef2f-4e40-b498-b26f1e3a80a0"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1e354cb-a258-418a-a3e7-df95e1452c9e"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fbc0d82-dd44-4487-817f-d11fa448714c"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a22f6d0f-4b33-4a98-be26-39728f673705"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""896410df-3992-48e6-8300-010ab86ae8c1"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39bee9a2-6a62-410d-8714-844c66a67962"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a70933ab-aed7-4518-8df2-9d20d73b2ade"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""skill4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ui"",
            ""id"": ""8599551e-834b-49c1-8751-355225326d55"",
            ""actions"": [
                {
                    ""name"": ""cancel"",
                    ""type"": ""Button"",
                    ""id"": ""aa992a5f-5098-40ff-863d-35e7832b7f05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""submit"",
                    ""type"": ""Button"",
                    ""id"": ""a3fa0a3c-2734-438a-8399-0907fe80b762"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pausegame"",
                    ""type"": ""Button"",
                    ""id"": ""4784bca8-9e0e-4c23-8bac-2229d8266473"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""da5ba6c5-7876-4c3d-b1f6-d65d2a2d6c13"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fee6ee8f-792b-4255-b842-2c7afd2027ba"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40b80ecf-3a51-426f-8445-62211922205e"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce3c8fec-b1d0-49e6-bc2d-e55b80d258e8"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b9ed2ec-7f1d-4959-896c-a6fd73544471"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pausegame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78645ad6-66a1-435e-b0bb-3931e6ec2406"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pausegame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // gameplay
        m_gameplay = asset.FindActionMap("gameplay", throwIfNotFound: true);
        m_gameplay_move = m_gameplay.FindAction("move", throwIfNotFound: true);
        m_gameplay_jump = m_gameplay.FindAction("jump", throwIfNotFound: true);
        m_gameplay_sprint = m_gameplay.FindAction("sprint", throwIfNotFound: true);
        m_gameplay_basicatk = m_gameplay.FindAction("basicatk", throwIfNotFound: true);
        m_gameplay_skill1 = m_gameplay.FindAction("skill1", throwIfNotFound: true);
        m_gameplay_skill2 = m_gameplay.FindAction("skill2", throwIfNotFound: true);
        m_gameplay_skill3 = m_gameplay.FindAction("skill3", throwIfNotFound: true);
        m_gameplay_skill4 = m_gameplay.FindAction("skill4", throwIfNotFound: true);
        // ui
        m_ui = asset.FindActionMap("ui", throwIfNotFound: true);
        m_ui_cancel = m_ui.FindAction("cancel", throwIfNotFound: true);
        m_ui_submit = m_ui.FindAction("submit", throwIfNotFound: true);
        m_ui_pausegame = m_ui.FindAction("pausegame", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gameplay
    private readonly InputActionMap m_gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_gameplay_move;
    private readonly InputAction m_gameplay_jump;
    private readonly InputAction m_gameplay_sprint;
    private readonly InputAction m_gameplay_basicatk;
    private readonly InputAction m_gameplay_skill1;
    private readonly InputAction m_gameplay_skill2;
    private readonly InputAction m_gameplay_skill3;
    private readonly InputAction m_gameplay_skill4;
    public struct GameplayActions
    {
        private @Controls m_Wrapper;
        public GameplayActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_gameplay_move;
        public InputAction @jump => m_Wrapper.m_gameplay_jump;
        public InputAction @sprint => m_Wrapper.m_gameplay_sprint;
        public InputAction @basicatk => m_Wrapper.m_gameplay_basicatk;
        public InputAction @skill1 => m_Wrapper.m_gameplay_skill1;
        public InputAction @skill2 => m_Wrapper.m_gameplay_skill2;
        public InputAction @skill3 => m_Wrapper.m_gameplay_skill3;
        public InputAction @skill4 => m_Wrapper.m_gameplay_skill4;
        public InputActionMap Get() { return m_Wrapper.m_gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @jump.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @jump.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @jump.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @sprint.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSprint;
                @sprint.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSprint;
                @sprint.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSprint;
                @basicatk.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBasicatk;
                @basicatk.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBasicatk;
                @basicatk.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBasicatk;
                @skill1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill1;
                @skill1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill1;
                @skill1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill1;
                @skill2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill2;
                @skill2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill2;
                @skill2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill2;
                @skill3.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill3;
                @skill3.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill3;
                @skill3.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill3;
                @skill4.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill4;
                @skill4.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill4;
                @skill4.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill4;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @jump.started += instance.OnJump;
                @jump.performed += instance.OnJump;
                @jump.canceled += instance.OnJump;
                @sprint.started += instance.OnSprint;
                @sprint.performed += instance.OnSprint;
                @sprint.canceled += instance.OnSprint;
                @basicatk.started += instance.OnBasicatk;
                @basicatk.performed += instance.OnBasicatk;
                @basicatk.canceled += instance.OnBasicatk;
                @skill1.started += instance.OnSkill1;
                @skill1.performed += instance.OnSkill1;
                @skill1.canceled += instance.OnSkill1;
                @skill2.started += instance.OnSkill2;
                @skill2.performed += instance.OnSkill2;
                @skill2.canceled += instance.OnSkill2;
                @skill3.started += instance.OnSkill3;
                @skill3.performed += instance.OnSkill3;
                @skill3.canceled += instance.OnSkill3;
                @skill4.started += instance.OnSkill4;
                @skill4.performed += instance.OnSkill4;
                @skill4.canceled += instance.OnSkill4;
            }
        }
    }
    public GameplayActions @gameplay => new GameplayActions(this);

    // ui
    private readonly InputActionMap m_ui;
    private IUiActions m_UiActionsCallbackInterface;
    private readonly InputAction m_ui_cancel;
    private readonly InputAction m_ui_submit;
    private readonly InputAction m_ui_pausegame;
    public struct UiActions
    {
        private @Controls m_Wrapper;
        public UiActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @cancel => m_Wrapper.m_ui_cancel;
        public InputAction @submit => m_Wrapper.m_ui_submit;
        public InputAction @pausegame => m_Wrapper.m_ui_pausegame;
        public InputActionMap Get() { return m_Wrapper.m_ui; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UiActions set) { return set.Get(); }
        public void SetCallbacks(IUiActions instance)
        {
            if (m_Wrapper.m_UiActionsCallbackInterface != null)
            {
                @cancel.started -= m_Wrapper.m_UiActionsCallbackInterface.OnCancel;
                @cancel.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnCancel;
                @cancel.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnCancel;
                @submit.started -= m_Wrapper.m_UiActionsCallbackInterface.OnSubmit;
                @submit.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnSubmit;
                @submit.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnSubmit;
                @pausegame.started -= m_Wrapper.m_UiActionsCallbackInterface.OnPausegame;
                @pausegame.performed -= m_Wrapper.m_UiActionsCallbackInterface.OnPausegame;
                @pausegame.canceled -= m_Wrapper.m_UiActionsCallbackInterface.OnPausegame;
            }
            m_Wrapper.m_UiActionsCallbackInterface = instance;
            if (instance != null)
            {
                @cancel.started += instance.OnCancel;
                @cancel.performed += instance.OnCancel;
                @cancel.canceled += instance.OnCancel;
                @submit.started += instance.OnSubmit;
                @submit.performed += instance.OnSubmit;
                @submit.canceled += instance.OnSubmit;
                @pausegame.started += instance.OnPausegame;
                @pausegame.performed += instance.OnPausegame;
                @pausegame.canceled += instance.OnPausegame;
            }
        }
    }
    public UiActions @ui => new UiActions(this);
    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnBasicatk(InputAction.CallbackContext context);
        void OnSkill1(InputAction.CallbackContext context);
        void OnSkill2(InputAction.CallbackContext context);
        void OnSkill3(InputAction.CallbackContext context);
        void OnSkill4(InputAction.CallbackContext context);
    }
    public interface IUiActions
    {
        void OnCancel(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnPausegame(InputAction.CallbackContext context);
    }
}
